config/routes.rb
Rails.application.routes.draw do
  get 'pending_purchase_orders/create'

  get 'pending_purchase_order/create'

  resources :purchase_orders
  resources :all_inventories
  root to: 'pages#home'
  resources :ftporders
  resources :orders
  resources :inventories
  resources :check
  resources :recepcion
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :shopping_cart_products
  resources :shopping_cart_order_items
  resource :carts, only: [:show]
  get 'portal/' => 'portal#index'
  get 'portal/new_attempt' => 'portal#new_attempt'
  get 'portal/infeasible_order' => 'portal#infeasible_order'

  get 'purchase_orders/(:format)/success' => 'purchase_orders#success'
  get 'purchase_orders/(:fail)/fail' => 'purchase_orders#fail'

end

app/models/all_inventory.rb
class AllInventory < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignation.rb
class Assignation < ApplicationRecord
end

app/models/group_id_oc.rb
class GroupIdOc < ApplicationRecord
end

app/models/handler.rb
class Handler < CheckController

  def empty_reception
    puts "------------- Empty Reception job ------------".green
    contador = 0
    for i in sku_with_stock(@@recepcion, @@api_key)[0]
      lista_productos = request_product(@@recepcion, i["_id"], @@api_key)[0]
      for j in lista_productos
        if contador <= 8
          move_product_almacen(j["_id"], @@despacho)
          move_product_almacen(j["_id"], @@pulmon)
          contador += 1
        end
      end
    end
    self.empty_reception()
  end
  handle_asynchronously :empty_reception, :run_at => Proc.new {1.minutes.from_now}

  def oc_pendientes
    puts "------------- Ordenes Pendientes job ------------".green
    pendientes()
    self.oc_pendientes()
  end
  handle_asynchronously :oc_pendientes, :run_at => Proc.new {100.minutes.from_now}

  def ordenes_de_compra_ftp
    puts "------------- Buscar Ordenes de Compra job ------------".green
    execute_ftp
    self.ordenes_de_compra_ftp
  end
  handle_asynchronously :ordenes_de_compra_ftp, :run_at => Proc.new {3.minutes.from_now}


  
  def satisfy_inventory_urgent_job
    puts "------------- Satisfy Inventory Level 1 urgent ------------".green
    satisfy_inventory_urgent()
    self.satisfy_inventory_urgent_job()
  end
  handle_asynchronously :satisfy_inventory_urgent_job, :run_at => Proc.new {4.minutes.from_now}


  def satisfy_inventory_level1_groups_job
    puts "------------- Satisfy Inventory Level 1 Groups job ------------".green
    satisfy_inventory_level1_groups()
    self.satisfy_inventory_level1_groups_job()
  end
  handle_asynchronously :satisfy_inventory_level1_groups_job, :run_at => Proc.new {4.minutes.from_now}

  def satisfy_inventory_level1_job
    puts "------------- Satisfy Inventory Level job ------------".green
    satisfy_inventory_level1()
    self.satisfy_inventory_level1_job
  end
  handle_asynchronously :satisfy_inventory_level1_job, :run_at => Proc.new {5.minutes.from_now}

  def satisfy_inventory_level2_job
    puts "------------- Satisfy Inventory Level 2 job ------------".green
    satisfy_inventory_level2()
    self.satisfy_inventory_level2_job
  end
  handle_asynchronously :satisfy_inventory_level2_job, :run_at => Proc.new {8.minutes.from_now}

  def arrocero
    puts "------------- Arrocero job ------------".green
    inventories = get_dict_inventories()
    product = Product.find_by sku: 1101
    product2 = Product.find_by sku: 1002
    in_cellar = inventories[product["sku"]] ? inventories[product["sku"]] : 0
    in_cellar2 = inventories[product2["sku"]] ? inventories[product2["sku"]] : 0
    if product["min"]*1.6 >= in_cellar and in_cellar < product["max"]
      fabricar_producto(10, 1101, 'despacho')
    end
    if product2["min"]*0.4 >= in_cellar2 and in_cellar2 < product2["max"]*0.4
      fabricar_producto(10, 1002, 'despacho')
    end
    self.arrocero
  end
handle_asynchronously :arrocero, :run_at => Proc.new {5.minutes.from_now}

  def delete_over_stock_job
    puts "------------- delete_over_stock_job ------------".green
    delete_over_stock()
    self.delete_over_stock_job
  end
  handle_asynchronously :delete_over_stock_job, :run_at => Proc.new {8.minutes.from_now}


  def portal_pendientes_job
    puts "------------- [PORTAL] Ordenes Pendientes job ------------".green
    portal_pendientes()
    self.portal_pendientes_job()
  end
  handle_asynchronously :portal_pendientes_job, :run_at => Proc.new {4.minutes.from_now}
  

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/inventory.rb
class Inventory < ApplicationRecord
end

app/models/minimum_stock.rb
class MinimumStock < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/pending_order.rb
class PendingOrder < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/product_joke.rb
class ProductJoke < ApplicationRecord
end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
end

app/models/receipt.rb
class Receipt < ApplicationRecord
end

app/models/shopping_cart_order.rb
class ShoppingCartOrder < ApplicationRecord
    has_many :shopping_cart_order_items
    before_save :set_subtotal

    def subtotal
        shopping_cart_order_items.collect {|order_item| order_item.valid? ? (order_item.unit_price * order_item.quantity) : 0}.sum
    end

    private
        def set_subtotal
            self[:subtotal] = subtotal
        end
end

app/controllers/all_inventories_controller.rb
class AllInventoriesController < CheckController
  before_action :set_all_inventory, only: [:show, :edit, :update, :destroy]

  # GET /all_inventories
  # GET /all_inventories.json
  def index
    @inventories = get_dict_inventories
    @products = Product.all.sort
    @recepcion = get_inventorie_from_cellar('recepcion')
    @pulmon = get_inventorie_from_cellar('pulmon')
    @cocina = get_inventorie_from_cellar('cocina')
    @despacho = get_inventorie_from_cellar('despacho')
    @old_pulmon = get_inventorie_from_cellar('old_pulmon')
  end

  # GET /all_inventories/1
  # GET /all_inventories/1.json
  def show
    pedir_un_producto(params[:id].to_i)
    @inventories = get_dict_inventories
    @product = Product.find_by sku: params[:id].to_i
  end

  # GET /all_inventories/new
  def new
    # @all_inventory = AllInventory.new
  end

  # GET /all_inventories/1/edit
  def edit
  end

  # POST /all_inventories
  # POST /all_inventories.json
  def create
    # @all_inventory = AllInventory.new(all_inventory_params)

    # respond_to do |format|
    #   if @all_inventory.save
    #     format.html { redirect_to @all_inventory, notice: 'All inventory was successfully created.' }
    #     format.json { render :show, status: :created, location: @all_inventory }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @all_inventory.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /all_inventories/1
  # PATCH/PUT /all_inventories/1.json
  def update
    # respond_to do |format|
    #   if @all_inventory.update(all_inventory_params)
    #     format.html { redirect_to @all_inventory, notice: 'All inventory was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @all_inventory }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @all_inventory.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /all_inventories/1
  # DELETE /all_inventories/1.json
  def destroy
    # @all_inventory.destroy
    # respond_to do |format|
    #   format.html { redirect_to all_inventories_url, notice: 'All inventory was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_all_inventory
      # @all_inventory = AllInventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def all_inventory_params
      # params.permit(:all_inventory, {:sku})
      params.permit(:sku)
    end
end

app/helpers/all_inventories_helper.rb
module AllInventoriesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/check_helper.rb
module CheckHelper
end

app/helpers/ftporders_helper.rb
module FtpordersHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/recepcion_helper.rb
module RecepcionHelper
end

app/views/all_inventories/_form.html.erb
<%= form_with(model: all_inventory, local: true) do |form| %>
  <% if all_inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(all_inventory.errors.count, "error") %> prohibited this all_inventory from being saved:</h2>

      <ul>
      <% all_inventory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/all_inventories/edit.html.erb
<h1>Editing All Inventory</h1>

<%= render 'form', all_inventory: @all_inventory %>

<%= link_to 'Show', @all_inventory %> |
<%= link_to 'Back', all_inventories_path %>

app/views/all_inventories/index.html.erb
<p id="notice"><%= notice %></p>
<h1>All Inventories</h1>
<table>
  <thead>
    <tr>
      <th>SKU</th>  
      <th>Name</th>
      <th>Quantity</th>
      <th>Min</th>
      <th>Faltan</th>
      <th>Details</th>
      <th>Recepción</th>
      <th>Pulmon</th>
      <th>Old Pulmon</th>
      <th>Cocina</th>
      <th>Despacho</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <% total = @inventories[product[:sku]] ? @inventories[product[:sku]] : 0   %>
      <tr>
        <td><%= product[:sku] %></td>
        <td><%= product[:name] %></td>
        <td><%= total %></td>
        <td><%= product[:min] %></td>
        <td><%= product[:min] - total> 0 ? product[:min] - total : 0%></td>
        <td><%= product[:description] %></td>
        <td><%= @recepcion[product[:sku]] ? @recepcion[product[:sku]] : 0 %></td>
        <td><%= @pulmon[product[:sku]] ? @pulmon[product[:sku]] : 0 %></td>
        <td><%= @old_pulmon[product[:sku]] ? @old_pulmon[product[:sku]] : 0 %></td>
        <td><%= @cocina[product[:sku]] ? @cocina[product[:sku]] : 0 %></td>
        <td><%= @despacho[product[:sku]] ? @despacho[product[:sku]] : 0 %></td>
        <td><%= link_to 'Pedir', all_inventory_path(product[:sku]) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/all_inventories/new.html.erb
<h1>New All Inventory</h1>

<%= render 'form', all_inventory: @all_inventory %>

<%= link_to 'Back', all_inventories_path %>

app/views/all_inventories/show.html.erb
<h1><%= "SKU: #{@product[:sku]}" %></h1>
<p><%= "Nombre: #{@product[:name]}" %></p>
<p><%= "Total: #{@inventories[@product[:sku]] ? @inventories[@product[:sku]] : 0}" %></p>

<%= link_to 'Back', all_inventories_path %>