config/routes.rb
Rails.application.routes.draw do
  get 'pending_purchase_orders/create'

  get 'pending_purchase_order/create'

  resources :purchase_orders
  resources :all_inventories
  root to: 'pages#home'
  resources :ftporders
  resources :orders
  resources :inventories
  resources :check
  resources :recepcion
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :shopping_cart_products
  resources :shopping_cart_order_items
  resource :carts, only: [:show]
  get 'portal/' => 'portal#index'
  get 'portal/new_attempt' => 'portal#new_attempt'
  get 'portal/infeasible_order' => 'portal#infeasible_order'

  get 'purchase_orders/(:format)/success' => 'purchase_orders#success'
  get 'purchase_orders/(:fail)/fail' => 'purchase_orders#fail'

end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
end

app/controllers/purchase_orders_controller.rb
require 'json'
require 'date'

class PurchaseOrdersController < ApplicationController
  before_action :set_purchase_order, only: [:show, :edit, :update, :destroy]

  include PurchaseOrdersHelper

  # GET /purchase_orders
  # GET /purchase_orders.json
  def index
    @purchase_orders = PurchaseOrder.all
  end

  # GET /purchase_orders/1.json
  def show
  end

  # GET /purchase_orders/new
  def new
    @sku_exists = false
    @order = ShoppingCartOrder.find(params[:order_id])
    @order_items = ShoppingCartOrderItem.where(shopping_cart_order_id: params[:order_id])
    @items_json = get_items_json(@order_items)
    if @order.shopping_cart_order_items.empty?
      redirect_to :controller => :portal, :action => :index
    else
      sku, quantity = get_sku_quantity(@order_items)
    end


    @purchase_order = PurchaseOrder.new
    @purchase_order.latitude = -33.4991118
    @purchase_order.longitude = -70.6183225
    
    # DEV: @purchase_order.proveedor = "5cbd31b7c445af0004739be3"
    # PROD: "5cc66e378820160004a4c3bc"
    @purchase_order.proveedor = "5cc66e378820160004a4c3bc"
    
    
    @purchase_order.total = @order.subtotal
    @purchase_order.quantity = quantity.to_i
    @purchase_order.sku = sku.to_s
    @purchase_order.products = @items_json #"{3001=> 1}"


  end

  # GET /purchase_orders/1/edit
  def edit
  end

  # POST /purchase_orders
  # POST /purchase_orders.json
  def create
    #si es feasible, cumplir el flujo existente, si no, redirigir al portal. Agregar otro flash por si no se puede fabricar
    
    puts "cantidad: #{purchase_order_params[:quantity]} y sku: #{purchase_order_params[:sku]}"
    feasible = check_dispatch_feasibility(purchase_order_params[:quantity].to_i, purchase_order_params[:sku].to_i)
    puts "El pedido es posible: #{feasible}."

    feasible = true

    if feasible
      @purchase_order = PurchaseOrder.new(purchase_order_params)
      if @purchase_order.save
        # Generar boleta
        code, body, headers = generar_boleta(@purchase_order.proveedor, @purchase_order.client, @purchase_order.total)
        puts code, body, headers
        puts 'se genero la boleta'
        if code.to_i == 200
          puts "se redirige a pagar"
          boleta_id = body["_id"]
          oc_id = body["oc"]
          purchased_at = DateTime.parse(body["created_at"])
          deadline = purchased_at + 90.minutes
          puts purchased_at&.class
          puts purchased_at
          puts deadline

          @purchase_order.purchased_at  = purchased_at
          @purchase_order.deadline = deadline
          @purchase_order.boleta_id = boleta_id
          @purchase_order.oc_id = oc_id
          @purchase_order.save
          puts "ID  BOLETA _id: #{boleta_id}"

          code2, body2, headers2 = pagar_orden(boleta_id, @purchase_order.id)
          puts 'se realizo el proceso de pago'
        end

      end
    else # feasible=false. Redirigir al portal
      redirect_to :controller => :portal, :action => :infeasible_order
    end
  end

  # PATCH/PUT /purchase_orders/1
  # PATCH/PUT /purchase_orders/1.json
  def update
    respond_to do |format|
      if @purchase_order.update(purchase_order_params)
        format.html { redirect_to @purchase_order, notice: 'Purchase order was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase_order }
      else
        format.html { render :edit }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchase_orders/1
  # DELETE /purchase_orders/1.json
  def destroy
    @purchase_order.destroy
    respond_to do |format|
      format.html { redirect_to purchase_orders_url, notice: 'Purchase order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def success
    puts "Parametros de éxito"
    puts params
    puts "---end---"
    
    @purchase_order = PurchaseOrder.find(params[:format].to_i)
    sku = @purchase_order.sku
    quantity = @purchase_order.quantity
    puts "se envia a fabricar"
    fabricate_purchase_order(quantity.to_i, sku.to_i)
    puts "ya se envio a fabricar"

    @purchase_order.created = true
    @purchase_order.save
    puts "purchase_order was created successfully loco alexissss."
    reset_session
  end

  def fail
    reset_session
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase_order
      @purchase_order = PurchaseOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_order_params
      params.require(:purchase_order).permit(:client, :latitude, :longitude, :total, :proveedor, :products, :sku, :quantity)
    end
end

app/helpers/purchase_orders_helper.rb
require 'json'

module PurchaseOrdersHelper

    def get_items_json order_items
        items_dict = {}
        order_items.each do |item|
            items_dict[item.shopping_cart_product.sku] = item.quantity
        end
        puts items_dict.to_json
        items_dict.to_json
    end

    def get_sku_quantity order_items
        sku = order_items[0].shopping_cart_product.sku
        quantity = order_items[0].quantity
        
        return sku, quantity
    end

    def generar_boleta(proveedor, cliente, total)
        # TODO: joaquin. CAMBIAR A "prod" CUANDO PASE A PROD
        @server_boleta = "prod"
    # hash_str = hash(method_str, api_key)
        puts "Se inicio la generación de boleta"
        uri = 'sii/boleta'
        base_url ="https://integracion-2019-#{@server_boleta}.herokuapp.com/"
        body = {
            "proveedor": proveedor,
            "cliente": cliente,
            "total": total
        }

        begin
            puts "Se envia el request"
            request = HTTParty.post(base_url+uri,
                body:body.to_json,
                headers:{
                "Content-Type": "application/json"
            })

            return request.code, JSON.parse(request.body) ,request.headers
        rescue JSON::ParserError => e
            puts "generar_boleta, error al parcear el body"
            return 500, {}, {}
        end
    end

    def pagar_orden(boleta_id, order_id)
        # TODO: joaquin. CAMBIAR A "prod" CUANDO PASE A PROD
        server = "prod"
        # TODO: joaquin. CAMBIAR A "prod" CUANDO PASE A PROD
        isLocal = "prod"

        success_url_local = "http%3A%2F%2F127.0.0.1%2Fpurchase_orders%2F#{order_id}%2Fsuccess"
        success_url_prod = "http%3A%2F%2Ftuerca1.ing.puc.cl%2Fpurchase_orders%2F#{order_id}%2Fsuccess"
        fail_url_local = "http%3A%2F%2F127.0.0.1%2Fpurchase_orders%2F#{order_id}%2Ffail"
        fail_url_prod = "http%3A%2F%2Ftuerca1.ing.puc.cl%2Fpurchase_orders%2F#{order_id}%2Ffail"

        
        url_ok = (isLocal == "local") ? success_url_local : success_url_prod
        url_fail = (isLocal == "local") ? fail_url_local : fail_url_prod
        
        payment_url = "https://integracion-2019-#{server}.herokuapp.com/web/pagoenlinea?callbackUrl=#{url_ok}&cancelUrl=#{url_fail}&boletaId=#{boleta_id}"

        redirect_to payment_url
    end

    def check_dispatch_feasibility (cantidad, sku)
        puts "se manda a evaluar el pedido"
        feasible = CheckController.new.evaluar_fabricar_final(cantidad, sku)
        puts "ya se evaluo..."
        feasible
    end

    def fabricate_purchase_order (cantidad, sku)
        puts "se manda a fabricar el pedido"
        CheckController.new.fabricar_final(cantidad, sku)
        puts "ya se mando a fabricar"
    end

end

app/views/purchase_orders/_form.html.erb
<% provide :head_tags do %>
    <meta name='turbolinks-visit-control' content='reload'>
    <script>
        document.addEventListener("DOMContentLoaded", initMap2);
    </script>
<% end %>

<%= form_with(model: purchase_order, local: true) do |form| %>
  <% if purchase_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(purchase_order.errors.count, "error") %> prohibited this purchase_order from being saved:</h2>

      <ul>
      <% purchase_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Indique su nombre" %>
    <%= form.text_field :client, id: :purchase_order_client, value: 'Señor X' %>
  </div>
  <br>
  <strong> Coordenadas de despacho </strong>
  <div class="field">
    <%= form.label "Latitud" %>
    <%= form.text_field :latitude, id: :purchase_order_latitude, :readonly => true%>
  </div>

  <div class="field">
    <%= form.label "Longitud" %>
    <%= form.text_field :longitude, id: :purchase_order_longitude, :readonly => true %>
  </div>

  <div>
    <%= form.hidden_field :products, value: @purchase_order.products %>
  </div>

  <div>
    <%= form.hidden_field :proveedor, value: @purchase_order.proveedor %>
  </div>

  <div>
    <%= form.hidden_field :total, value: @purchase_order.total %>
  </div>

  <div>
    <%= form.hidden_field :sku, value: @purchase_order.sku %>
  </div>

  <div>
    <%= form.hidden_field :quantity, value: @purchase_order.quantity %>
  </div>

  <p>
    <div id="map2"> </div>
  </p>

  <div class="actions">
    <%= form.submit "Ir a pagar", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/purchase_orders/edit.html.erb
<h1>Editing Purchase Order</h1>

<%= render 'form', purchase_order: @purchase_order %>

<%= link_to 'Show', @purchase_order %> |
<%= link_to 'Back', purchase_orders_path %>

app/views/purchase_orders/fail.html.erb
<div class="jumbotron text-xs-center">
  <h1 class="display-3">El banco no ha podido procesar tu compra...</h1>
  <p class="lead"><strong>Lo lamentamos...</strong></p>
  <hr>
  <p>
    De todas formas, puedes <p><strong>calificarnos con un 7 :) </strong></p>
  </p>
  <p class="lead">
    <%= button_to('Quieres intentar otra compra?', { controller: :portal, action: 'new_attempt'}, {method: :get, params: {order_id: current_order.id}, class: 'btn btn-primary'}) %>
  </p>
</div>

app/views/purchase_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Purchase Orders</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Total</th>
      <th>Proveedor</th>
      <th>Products</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchase_orders.each do |purchase_order| %>
      <tr>
        <td><%= purchase_order.client %></td>
        <td><%= purchase_order.latitude %></td>
        <td><%= purchase_order.longitude %></td>
        <td><%= purchase_order.total %></td>
        <td><%= purchase_order.proveedor %></td>
        <td><%= purchase_order.products %></td>
        <td><%= link_to 'Show', purchase_order %></td>
        <td><%= link_to 'Edit', edit_purchase_order_path(purchase_order) %></td>
        <td><%= link_to 'Destroy', purchase_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase Order', new_purchase_order_path %>

app/views/purchase_orders/new.html.erb
<% provide :head_tags do %>
    <meta name='turbolinks-visit-control' content='reload'>
    <script>
    document.addEventListener("DOMContentLoaded", function(){
        initMap2(<%=@purchase_order.latitude%>, <%=@purchase_order.longitude%>)
    });
    </script>
<% end %>

<h1>Estás a punto de confirmar tu compra de sushi!</h1>
<br><br>
<h4> A continuación, rellena tus datos</h4> 
<p>1. Ingresa tu nombre, y </p>
<p>2. Selecciona tu dirección de despacho en el mapa</p>

<%= render 'form', purchase_order: @purchase_order %>

<%= button_to('Volver al portal', { controller: :portal, action: 'index'}, {method: :get, class: 'btn btn-danger'}) %>

app/views/purchase_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @purchase_order.client %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @purchase_order.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @purchase_order.longitude %>
</p>

<p>
  <strong>Total:</strong>
  <%= @purchase_order.total %>
</p>

<p>
  <strong>Proveedor:</strong>
  <%= @purchase_order.proveedor %>
</p>

<p>
  <strong>Products:</strong>
  <%= @purchase_order.products %>
</p>

<%= link_to 'Edit', edit_purchase_order_path(@purchase_order) %> |
<%= link_to 'Back', purchase_orders_path %>

app/views/purchase_orders/success.html.erb
<div class="jumbotron text-xs-center">
  <h1 class="display-3">Tu compra se ha realizado con éxito!</h1>
  <p class="lead"><strong>Tu pedido será despachado pronto</strong></p>
  <hr>
  <p>
    <strong>Tu experiencia de compra fue agradable? </strong><p> Calificanos con un 7 :) </p>
  </p>
  <p class="lead">
    <%= button_to('Quieres hacer otra compra?', { controller: :portal, action: :new_attempt}, {method: :get, params: {order_id: current_order.id}, class: 'btn btn-primary'}) %>
  </p>
</div>